//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.31 at 02:33:03 PM AEDT 
//


package au.csiro.fhir.transforms.xml.dmd.vtming.v1_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VTM_ING" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VTMID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="ISID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vtming"
})
@XmlRootElement(name = "VTM_INGREDIENTS")
public class VTMINGREDIENTS {

    @XmlElement(name = "VTM_ING")
    protected List<VTMINGREDIENTS.VTMING> vtming;

    /**
     * Gets the value of the vtming property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vtming property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVTMING().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VTMINGREDIENTS.VTMING }
     * 
     * 
     */
    public List<VTMINGREDIENTS.VTMING> getVTMING() {
        if (vtming == null) {
            vtming = new ArrayList<VTMINGREDIENTS.VTMING>();
        }
        return this.vtming;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VTMID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="ISID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vtmid",
        "isid"
    })
    public static class VTMING {

        @XmlElement(name = "VTMID", required = true)
        protected BigInteger vtmid;
        @XmlElement(name = "ISID", required = true)
        protected BigInteger isid;

        /**
         * Gets the value of the vtmid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVTMID() {
            return vtmid;
        }

        /**
         * Sets the value of the vtmid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVTMID(BigInteger value) {
            this.vtmid = value;
        }

        /**
         * Gets the value of the isid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getISID() {
            return isid;
        }

        /**
         * Sets the value of the isid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setISID(BigInteger value) {
            this.isid = value;
        }

    }

}
