//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.19 at 02:36:54 PM AEDT 
//


package au.csiro.fhir.transforms.xml.dmd.history.v1_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HISTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HISTType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="IDCURRENT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="IDPREVIOUS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="STARTDT" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ENDDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HISTType", propOrder = {

})
public class HISTType {

    @XmlElement(name = "IDCURRENT", required = true)
    protected BigInteger idcurrent;
    @XmlElement(name = "IDPREVIOUS", required = true)
    protected BigInteger idprevious;
    @XmlElement(name = "STARTDT", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startdt;
    @XmlElement(name = "ENDDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar enddt;

    /**
     * Gets the value of the idcurrent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIDCURRENT() {
        return idcurrent;
    }

    /**
     * Sets the value of the idcurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDCURRENT(BigInteger value) {
        this.idcurrent = value;
    }

    /**
     * Gets the value of the idprevious property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIDPREVIOUS() {
        return idprevious;
    }

    /**
     * Sets the value of the idprevious property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDPREVIOUS(BigInteger value) {
        this.idprevious = value;
    }

    /**
     * Gets the value of the startdt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSTARTDT() {
        return startdt;
    }

    /**
     * Sets the value of the startdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSTARTDT(XMLGregorianCalendar value) {
        this.startdt = value;
    }

    /**
     * Gets the value of the enddt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getENDDT() {
        return enddt;
    }

    /**
     * Sets the value of the enddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setENDDT(XMLGregorianCalendar value) {
        this.enddt = value;
    }

}
