//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.19 at 02:36:54 PM AEDT 
//


package au.csiro.fhir.transforms.xml.dmd.history.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VTMS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VTM" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VMPS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VMP" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="INGS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ING" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SUPPS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SUPP" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FORMS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FORM" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ROUTES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ROUTE" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UOMS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UOM" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vtms",
    "vmps",
    "ings",
    "supps",
    "forms",
    "routes",
    "uoms"
})
@XmlRootElement(name = "HISTORY")
public class HISTORY {

    @XmlElement(name = "VTMS", required = true)
    protected HISTORY.VTMS vtms;
    @XmlElement(name = "VMPS", required = true)
    protected HISTORY.VMPS vmps;
    @XmlElement(name = "INGS", required = true)
    protected HISTORY.INGS ings;
    @XmlElement(name = "SUPPS", required = true)
    protected HISTORY.SUPPS supps;
    @XmlElement(name = "FORMS", required = true)
    protected HISTORY.FORMS forms;
    @XmlElement(name = "ROUTES", required = true)
    protected HISTORY.ROUTES routes;
    @XmlElement(name = "UOMS", required = true)
    protected HISTORY.UOMS uoms;

    /**
     * Gets the value of the vtms property.
     * 
     * @return
     *     possible object is
     *     {@link HISTORY.VTMS }
     *     
     */
    public HISTORY.VTMS getVTMS() {
        return vtms;
    }

    /**
     * Sets the value of the vtms property.
     * 
     * @param value
     *     allowed object is
     *     {@link HISTORY.VTMS }
     *     
     */
    public void setVTMS(HISTORY.VTMS value) {
        this.vtms = value;
    }

    /**
     * Gets the value of the vmps property.
     * 
     * @return
     *     possible object is
     *     {@link HISTORY.VMPS }
     *     
     */
    public HISTORY.VMPS getVMPS() {
        return vmps;
    }

    /**
     * Sets the value of the vmps property.
     * 
     * @param value
     *     allowed object is
     *     {@link HISTORY.VMPS }
     *     
     */
    public void setVMPS(HISTORY.VMPS value) {
        this.vmps = value;
    }

    /**
     * Gets the value of the ings property.
     * 
     * @return
     *     possible object is
     *     {@link HISTORY.INGS }
     *     
     */
    public HISTORY.INGS getINGS() {
        return ings;
    }

    /**
     * Sets the value of the ings property.
     * 
     * @param value
     *     allowed object is
     *     {@link HISTORY.INGS }
     *     
     */
    public void setINGS(HISTORY.INGS value) {
        this.ings = value;
    }

    /**
     * Gets the value of the supps property.
     * 
     * @return
     *     possible object is
     *     {@link HISTORY.SUPPS }
     *     
     */
    public HISTORY.SUPPS getSUPPS() {
        return supps;
    }

    /**
     * Sets the value of the supps property.
     * 
     * @param value
     *     allowed object is
     *     {@link HISTORY.SUPPS }
     *     
     */
    public void setSUPPS(HISTORY.SUPPS value) {
        this.supps = value;
    }

    /**
     * Gets the value of the forms property.
     * 
     * @return
     *     possible object is
     *     {@link HISTORY.FORMS }
     *     
     */
    public HISTORY.FORMS getFORMS() {
        return forms;
    }

    /**
     * Sets the value of the forms property.
     * 
     * @param value
     *     allowed object is
     *     {@link HISTORY.FORMS }
     *     
     */
    public void setFORMS(HISTORY.FORMS value) {
        this.forms = value;
    }

    /**
     * Gets the value of the routes property.
     * 
     * @return
     *     possible object is
     *     {@link HISTORY.ROUTES }
     *     
     */
    public HISTORY.ROUTES getROUTES() {
        return routes;
    }

    /**
     * Sets the value of the routes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HISTORY.ROUTES }
     *     
     */
    public void setROUTES(HISTORY.ROUTES value) {
        this.routes = value;
    }

    /**
     * Gets the value of the uoms property.
     * 
     * @return
     *     possible object is
     *     {@link HISTORY.UOMS }
     *     
     */
    public HISTORY.UOMS getUOMS() {
        return uoms;
    }

    /**
     * Sets the value of the uoms property.
     * 
     * @param value
     *     allowed object is
     *     {@link HISTORY.UOMS }
     *     
     */
    public void setUOMS(HISTORY.UOMS value) {
        this.uoms = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FORM" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "form"
    })
    public static class FORMS {

        @XmlElement(name = "FORM")
        protected List<HISTType> form;

        /**
         * Gets the value of the form property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the form property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFORM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HISTType }
         * 
         * 
         */
        public List<HISTType> getFORM() {
            if (form == null) {
                form = new ArrayList<HISTType>();
            }
            return this.form;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ING" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ing"
    })
    public static class INGS {

        @XmlElement(name = "ING")
        protected List<HISTType> ing;

        /**
         * Gets the value of the ing property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ing property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getING().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HISTType }
         * 
         * 
         */
        public List<HISTType> getING() {
            if (ing == null) {
                ing = new ArrayList<HISTType>();
            }
            return this.ing;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ROUTE" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "route"
    })
    public static class ROUTES {

        @XmlElement(name = "ROUTE")
        protected List<HISTType> route;

        /**
         * Gets the value of the route property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the route property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getROUTE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HISTType }
         * 
         * 
         */
        public List<HISTType> getROUTE() {
            if (route == null) {
                route = new ArrayList<HISTType>();
            }
            return this.route;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SUPP" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supp"
    })
    public static class SUPPS {

        @XmlElement(name = "SUPP")
        protected List<HISTType> supp;

        /**
         * Gets the value of the supp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSUPP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HISTType }
         * 
         * 
         */
        public List<HISTType> getSUPP() {
            if (supp == null) {
                supp = new ArrayList<HISTType>();
            }
            return this.supp;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UOM" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uom"
    })
    public static class UOMS {

        @XmlElement(name = "UOM")
        protected List<HISTType> uom;

        /**
         * Gets the value of the uom property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uom property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUOM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HISTType }
         * 
         * 
         */
        public List<HISTType> getUOM() {
            if (uom == null) {
                uom = new ArrayList<HISTType>();
            }
            return this.uom;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VMP" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vmp"
    })
    public static class VMPS {

        @XmlElement(name = "VMP")
        protected List<HISTType> vmp;

        /**
         * Gets the value of the vmp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vmp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVMP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HISTType }
         * 
         * 
         */
        public List<HISTType> getVMP() {
            if (vmp == null) {
                vmp = new ArrayList<HISTType>();
            }
            return this.vmp;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VTM" type="{}HISTType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vtm"
    })
    public static class VTMS {

        @XmlElement(name = "VTM")
        protected List<HISTType> vtm;

        /**
         * Gets the value of the vtm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vtm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVTM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HISTType }
         * 
         * 
         */
        public List<HISTType> getVTM() {
            if (vtm == null) {
                vtm = new ArrayList<HISTType>();
            }
            return this.vtm;
        }

    }

}
