//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.02 at 04:17:57 PM AEDT 
//


package au.csiro.fhir.transforms.xml.dmd.history.v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HISTORY }
     * 
     */
    public HISTORY createHISTORY() {
        return new HISTORY();
    }

    /**
     * Create an instance of {@link HISTORY.VTMS }
     * 
     */
    public HISTORY.VTMS createHISTORYVTMS() {
        return new HISTORY.VTMS();
    }

    /**
     * Create an instance of {@link HISTORY.VMPS }
     * 
     */
    public HISTORY.VMPS createHISTORYVMPS() {
        return new HISTORY.VMPS();
    }

    /**
     * Create an instance of {@link HISTORY.INGS }
     * 
     */
    public HISTORY.INGS createHISTORYINGS() {
        return new HISTORY.INGS();
    }

    /**
     * Create an instance of {@link HISTORY.SUPPS }
     * 
     */
    public HISTORY.SUPPS createHISTORYSUPPS() {
        return new HISTORY.SUPPS();
    }

    /**
     * Create an instance of {@link HISTORY.FORMS }
     * 
     */
    public HISTORY.FORMS createHISTORYFORMS() {
        return new HISTORY.FORMS();
    }

    /**
     * Create an instance of {@link HISTORY.ROUTES }
     * 
     */
    public HISTORY.ROUTES createHISTORYROUTES() {
        return new HISTORY.ROUTES();
    }

    /**
     * Create an instance of {@link HISTORY.UOMS }
     * 
     */
    public HISTORY.UOMS createHISTORYUOMS() {
        return new HISTORY.UOMS();
    }

    /**
     * Create an instance of {@link HISTType }
     * 
     */
    public HISTType createHISTType() {
        return new HISTType();
    }

}
