//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.lookup;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="COMBINATION_PACK_IND"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="COMBINATION_PROD_IND"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BASIS_OF_NAME"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NAMECHANGE_REASON"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="VIRTUAL_PRODUCT_PRES_STATUS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CONTROL_DRUG_CATEGORY"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LICENSING_AUTHORITY"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UNIT_OF_MEASURE"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}HistoryInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FORM"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}HistoryInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ONT_FORM_ROUTE"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ROUTE"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}HistoryInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DT_PAYMENT_CATEGORY"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SUPPLIER"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}SupplierInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FLAVOUR"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="COLOUR"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BASIS_OF_STRNTH"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="REIMBURSEMENT_STATUS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SPEC_CONT"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DND"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="VIRTUAL_PRODUCT_NON_AVAIL"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DISCONTINUED_IND"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DF_INDICATOR"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PRICE_BASIS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LEGAL_CATEGORY"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AVAILABILITY_RESTRICTION"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LICENSING_AUTHORITY_CHANGE_REASON"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "combinationpackind",
    "combinationprodind",
    "basisofname",
    "namechangereason",
    "virtualproductpresstatus",
    "controldrugcategory",
    "licensingauthority",
    "unitofmeasure",
    "form",
    "ontformroute",
    "route",
    "dtpaymentcategory",
    "supplier",
    "flavour",
    "colour",
    "basisofstrnth",
    "reimbursementstatus",
    "speccont",
    "dnd",
    "virtualproductnonavail",
    "discontinuedind",
    "dfindicator",
    "pricebasis",
    "legalcategory",
    "availabilityrestriction",
    "licensingauthoritychangereason"
})
@XmlRootElement(name = "LOOKUP")
public class LOOKUP {

    @XmlElement(name = "COMBINATION_PACK_IND", required = true)
    protected LOOKUP.COMBINATIONPACKIND combinationpackind;
    @XmlElement(name = "COMBINATION_PROD_IND", required = true)
    protected LOOKUP.COMBINATIONPRODIND combinationprodind;
    @XmlElement(name = "BASIS_OF_NAME", required = true)
    protected LOOKUP.BASISOFNAME basisofname;
    @XmlElement(name = "NAMECHANGE_REASON", required = true)
    protected LOOKUP.NAMECHANGEREASON namechangereason;
    @XmlElement(name = "VIRTUAL_PRODUCT_PRES_STATUS", required = true)
    protected LOOKUP.VIRTUALPRODUCTPRESSTATUS virtualproductpresstatus;
    @XmlElement(name = "CONTROL_DRUG_CATEGORY", required = true)
    protected LOOKUP.CONTROLDRUGCATEGORY controldrugcategory;
    @XmlElement(name = "LICENSING_AUTHORITY", required = true)
    protected LOOKUP.LICENSINGAUTHORITY licensingauthority;
    @XmlElement(name = "UNIT_OF_MEASURE", required = true)
    protected LOOKUP.UNITOFMEASURE unitofmeasure;
    @XmlElement(name = "FORM", required = true)
    protected LOOKUP.FORM form;
    @XmlElement(name = "ONT_FORM_ROUTE", required = true)
    protected LOOKUP.ONTFORMROUTE ontformroute;
    @XmlElement(name = "ROUTE", required = true)
    protected LOOKUP.ROUTE route;
    @XmlElement(name = "DT_PAYMENT_CATEGORY", required = true)
    protected LOOKUP.DTPAYMENTCATEGORY dtpaymentcategory;
    @XmlElement(name = "SUPPLIER", required = true)
    protected LOOKUP.SUPPLIER supplier;
    @XmlElement(name = "FLAVOUR", required = true)
    protected LOOKUP.FLAVOUR flavour;
    @XmlElement(name = "COLOUR", required = true)
    protected LOOKUP.COLOUR colour;
    @XmlElement(name = "BASIS_OF_STRNTH", required = true)
    protected LOOKUP.BASISOFSTRNTH basisofstrnth;
    @XmlElement(name = "REIMBURSEMENT_STATUS", required = true)
    protected LOOKUP.REIMBURSEMENTSTATUS reimbursementstatus;
    @XmlElement(name = "SPEC_CONT", required = true)
    protected LOOKUP.SPECCONT speccont;
    @XmlElement(name = "DND", required = true)
    protected LOOKUP.DND dnd;
    @XmlElement(name = "VIRTUAL_PRODUCT_NON_AVAIL", required = true)
    protected LOOKUP.VIRTUALPRODUCTNONAVAIL virtualproductnonavail;
    @XmlElement(name = "DISCONTINUED_IND", required = true)
    protected LOOKUP.DISCONTINUEDIND discontinuedind;
    @XmlElement(name = "DF_INDICATOR", required = true)
    protected LOOKUP.DFINDICATOR dfindicator;
    @XmlElement(name = "PRICE_BASIS", required = true)
    protected LOOKUP.PRICEBASIS pricebasis;
    @XmlElement(name = "LEGAL_CATEGORY", required = true)
    protected LOOKUP.LEGALCATEGORY legalcategory;
    @XmlElement(name = "AVAILABILITY_RESTRICTION", required = true)
    protected LOOKUP.AVAILABILITYRESTRICTION availabilityrestriction;
    @XmlElement(name = "LICENSING_AUTHORITY_CHANGE_REASON", required = true)
    protected LOOKUP.LICENSINGAUTHORITYCHANGEREASON licensingauthoritychangereason;

    /**
     * Gets the value of the combinationpackind property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.COMBINATIONPACKIND }
     *     
     */
    public LOOKUP.COMBINATIONPACKIND getCOMBINATIONPACKIND() {
        return combinationpackind;
    }

    /**
     * Sets the value of the combinationpackind property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.COMBINATIONPACKIND }
     *     
     */
    public void setCOMBINATIONPACKIND(LOOKUP.COMBINATIONPACKIND value) {
        this.combinationpackind = value;
    }

    /**
     * Gets the value of the combinationprodind property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.COMBINATIONPRODIND }
     *     
     */
    public LOOKUP.COMBINATIONPRODIND getCOMBINATIONPRODIND() {
        return combinationprodind;
    }

    /**
     * Sets the value of the combinationprodind property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.COMBINATIONPRODIND }
     *     
     */
    public void setCOMBINATIONPRODIND(LOOKUP.COMBINATIONPRODIND value) {
        this.combinationprodind = value;
    }

    /**
     * Gets the value of the basisofname property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.BASISOFNAME }
     *     
     */
    public LOOKUP.BASISOFNAME getBASISOFNAME() {
        return basisofname;
    }

    /**
     * Sets the value of the basisofname property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.BASISOFNAME }
     *     
     */
    public void setBASISOFNAME(LOOKUP.BASISOFNAME value) {
        this.basisofname = value;
    }

    /**
     * Gets the value of the namechangereason property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.NAMECHANGEREASON }
     *     
     */
    public LOOKUP.NAMECHANGEREASON getNAMECHANGEREASON() {
        return namechangereason;
    }

    /**
     * Sets the value of the namechangereason property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.NAMECHANGEREASON }
     *     
     */
    public void setNAMECHANGEREASON(LOOKUP.NAMECHANGEREASON value) {
        this.namechangereason = value;
    }

    /**
     * Gets the value of the virtualproductpresstatus property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.VIRTUALPRODUCTPRESSTATUS }
     *     
     */
    public LOOKUP.VIRTUALPRODUCTPRESSTATUS getVIRTUALPRODUCTPRESSTATUS() {
        return virtualproductpresstatus;
    }

    /**
     * Sets the value of the virtualproductpresstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.VIRTUALPRODUCTPRESSTATUS }
     *     
     */
    public void setVIRTUALPRODUCTPRESSTATUS(LOOKUP.VIRTUALPRODUCTPRESSTATUS value) {
        this.virtualproductpresstatus = value;
    }

    /**
     * Gets the value of the controldrugcategory property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.CONTROLDRUGCATEGORY }
     *     
     */
    public LOOKUP.CONTROLDRUGCATEGORY getCONTROLDRUGCATEGORY() {
        return controldrugcategory;
    }

    /**
     * Sets the value of the controldrugcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.CONTROLDRUGCATEGORY }
     *     
     */
    public void setCONTROLDRUGCATEGORY(LOOKUP.CONTROLDRUGCATEGORY value) {
        this.controldrugcategory = value;
    }

    /**
     * Gets the value of the licensingauthority property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.LICENSINGAUTHORITY }
     *     
     */
    public LOOKUP.LICENSINGAUTHORITY getLICENSINGAUTHORITY() {
        return licensingauthority;
    }

    /**
     * Sets the value of the licensingauthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.LICENSINGAUTHORITY }
     *     
     */
    public void setLICENSINGAUTHORITY(LOOKUP.LICENSINGAUTHORITY value) {
        this.licensingauthority = value;
    }

    /**
     * Gets the value of the unitofmeasure property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.UNITOFMEASURE }
     *     
     */
    public LOOKUP.UNITOFMEASURE getUNITOFMEASURE() {
        return unitofmeasure;
    }

    /**
     * Sets the value of the unitofmeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.UNITOFMEASURE }
     *     
     */
    public void setUNITOFMEASURE(LOOKUP.UNITOFMEASURE value) {
        this.unitofmeasure = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.FORM }
     *     
     */
    public LOOKUP.FORM getFORM() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.FORM }
     *     
     */
    public void setFORM(LOOKUP.FORM value) {
        this.form = value;
    }

    /**
     * Gets the value of the ontformroute property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.ONTFORMROUTE }
     *     
     */
    public LOOKUP.ONTFORMROUTE getONTFORMROUTE() {
        return ontformroute;
    }

    /**
     * Sets the value of the ontformroute property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.ONTFORMROUTE }
     *     
     */
    public void setONTFORMROUTE(LOOKUP.ONTFORMROUTE value) {
        this.ontformroute = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.ROUTE }
     *     
     */
    public LOOKUP.ROUTE getROUTE() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.ROUTE }
     *     
     */
    public void setROUTE(LOOKUP.ROUTE value) {
        this.route = value;
    }

    /**
     * Gets the value of the dtpaymentcategory property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.DTPAYMENTCATEGORY }
     *     
     */
    public LOOKUP.DTPAYMENTCATEGORY getDTPAYMENTCATEGORY() {
        return dtpaymentcategory;
    }

    /**
     * Sets the value of the dtpaymentcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.DTPAYMENTCATEGORY }
     *     
     */
    public void setDTPAYMENTCATEGORY(LOOKUP.DTPAYMENTCATEGORY value) {
        this.dtpaymentcategory = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.SUPPLIER }
     *     
     */
    public LOOKUP.SUPPLIER getSUPPLIER() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.SUPPLIER }
     *     
     */
    public void setSUPPLIER(LOOKUP.SUPPLIER value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the flavour property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.FLAVOUR }
     *     
     */
    public LOOKUP.FLAVOUR getFLAVOUR() {
        return flavour;
    }

    /**
     * Sets the value of the flavour property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.FLAVOUR }
     *     
     */
    public void setFLAVOUR(LOOKUP.FLAVOUR value) {
        this.flavour = value;
    }

    /**
     * Gets the value of the colour property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.COLOUR }
     *     
     */
    public LOOKUP.COLOUR getCOLOUR() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.COLOUR }
     *     
     */
    public void setCOLOUR(LOOKUP.COLOUR value) {
        this.colour = value;
    }

    /**
     * Gets the value of the basisofstrnth property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.BASISOFSTRNTH }
     *     
     */
    public LOOKUP.BASISOFSTRNTH getBASISOFSTRNTH() {
        return basisofstrnth;
    }

    /**
     * Sets the value of the basisofstrnth property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.BASISOFSTRNTH }
     *     
     */
    public void setBASISOFSTRNTH(LOOKUP.BASISOFSTRNTH value) {
        this.basisofstrnth = value;
    }

    /**
     * Gets the value of the reimbursementstatus property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.REIMBURSEMENTSTATUS }
     *     
     */
    public LOOKUP.REIMBURSEMENTSTATUS getREIMBURSEMENTSTATUS() {
        return reimbursementstatus;
    }

    /**
     * Sets the value of the reimbursementstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.REIMBURSEMENTSTATUS }
     *     
     */
    public void setREIMBURSEMENTSTATUS(LOOKUP.REIMBURSEMENTSTATUS value) {
        this.reimbursementstatus = value;
    }

    /**
     * Gets the value of the speccont property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.SPECCONT }
     *     
     */
    public LOOKUP.SPECCONT getSPECCONT() {
        return speccont;
    }

    /**
     * Sets the value of the speccont property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.SPECCONT }
     *     
     */
    public void setSPECCONT(LOOKUP.SPECCONT value) {
        this.speccont = value;
    }

    /**
     * Gets the value of the dnd property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.DND }
     *     
     */
    public LOOKUP.DND getDND() {
        return dnd;
    }

    /**
     * Sets the value of the dnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.DND }
     *     
     */
    public void setDND(LOOKUP.DND value) {
        this.dnd = value;
    }

    /**
     * Gets the value of the virtualproductnonavail property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.VIRTUALPRODUCTNONAVAIL }
     *     
     */
    public LOOKUP.VIRTUALPRODUCTNONAVAIL getVIRTUALPRODUCTNONAVAIL() {
        return virtualproductnonavail;
    }

    /**
     * Sets the value of the virtualproductnonavail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.VIRTUALPRODUCTNONAVAIL }
     *     
     */
    public void setVIRTUALPRODUCTNONAVAIL(LOOKUP.VIRTUALPRODUCTNONAVAIL value) {
        this.virtualproductnonavail = value;
    }

    /**
     * Gets the value of the discontinuedind property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.DISCONTINUEDIND }
     *     
     */
    public LOOKUP.DISCONTINUEDIND getDISCONTINUEDIND() {
        return discontinuedind;
    }

    /**
     * Sets the value of the discontinuedind property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.DISCONTINUEDIND }
     *     
     */
    public void setDISCONTINUEDIND(LOOKUP.DISCONTINUEDIND value) {
        this.discontinuedind = value;
    }

    /**
     * Gets the value of the dfindicator property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.DFINDICATOR }
     *     
     */
    public LOOKUP.DFINDICATOR getDFINDICATOR() {
        return dfindicator;
    }

    /**
     * Sets the value of the dfindicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.DFINDICATOR }
     *     
     */
    public void setDFINDICATOR(LOOKUP.DFINDICATOR value) {
        this.dfindicator = value;
    }

    /**
     * Gets the value of the pricebasis property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.PRICEBASIS }
     *     
     */
    public LOOKUP.PRICEBASIS getPRICEBASIS() {
        return pricebasis;
    }

    /**
     * Sets the value of the pricebasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.PRICEBASIS }
     *     
     */
    public void setPRICEBASIS(LOOKUP.PRICEBASIS value) {
        this.pricebasis = value;
    }

    /**
     * Gets the value of the legalcategory property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.LEGALCATEGORY }
     *     
     */
    public LOOKUP.LEGALCATEGORY getLEGALCATEGORY() {
        return legalcategory;
    }

    /**
     * Sets the value of the legalcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.LEGALCATEGORY }
     *     
     */
    public void setLEGALCATEGORY(LOOKUP.LEGALCATEGORY value) {
        this.legalcategory = value;
    }

    /**
     * Gets the value of the availabilityrestriction property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.AVAILABILITYRESTRICTION }
     *     
     */
    public LOOKUP.AVAILABILITYRESTRICTION getAVAILABILITYRESTRICTION() {
        return availabilityrestriction;
    }

    /**
     * Sets the value of the availabilityrestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.AVAILABILITYRESTRICTION }
     *     
     */
    public void setAVAILABILITYRESTRICTION(LOOKUP.AVAILABILITYRESTRICTION value) {
        this.availabilityrestriction = value;
    }

    /**
     * Gets the value of the licensingauthoritychangereason property.
     * 
     * @return
     *     possible object is
     *     {@link LOOKUP.LICENSINGAUTHORITYCHANGEREASON }
     *     
     */
    public LOOKUP.LICENSINGAUTHORITYCHANGEREASON getLICENSINGAUTHORITYCHANGEREASON() {
        return licensingauthoritychangereason;
    }

    /**
     * Sets the value of the licensingauthoritychangereason property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOKUP.LICENSINGAUTHORITYCHANGEREASON }
     *     
     */
    public void setLICENSINGAUTHORITYCHANGEREASON(LOOKUP.LICENSINGAUTHORITYCHANGEREASON value) {
        this.licensingauthoritychangereason = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class AVAILABILITYRESTRICTION {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class BASISOFNAME {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class BASISOFSTRNTH {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class COLOUR {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class COMBINATIONPACKIND {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class COMBINATIONPRODIND {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class CONTROLDRUGCATEGORY {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class DFINDICATOR {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class DISCONTINUEDIND {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class DND {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class DTPAYMENTCATEGORY {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class FLAVOUR {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}HistoryInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class FORM {

        @XmlElement(name = "INFO")
        protected List<HistoryInfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HistoryInfoType }
         * 
         * 
         */
        public List<HistoryInfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<HistoryInfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class LEGALCATEGORY {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class LICENSINGAUTHORITY {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class LICENSINGAUTHORITYCHANGEREASON {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class NAMECHANGEREASON {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class ONTFORMROUTE {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class PRICEBASIS {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class REIMBURSEMENTSTATUS {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}HistoryInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class ROUTE {

        @XmlElement(name = "INFO")
        protected List<HistoryInfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HistoryInfoType }
         * 
         * 
         */
        public List<HistoryInfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<HistoryInfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class SPECCONT {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}SupplierInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class SUPPLIER {

        @XmlElement(name = "INFO")
        protected List<SupplierInfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SupplierInfoType }
         * 
         * 
         */
        public List<SupplierInfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<SupplierInfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}HistoryInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class UNITOFMEASURE {

        @XmlElement(name = "INFO")
        protected List<HistoryInfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HistoryInfoType }
         * 
         * 
         */
        public List<HistoryInfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<HistoryInfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class VIRTUALPRODUCTNONAVAIL {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INFO" type="{}InfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info"
    })
    public static class VIRTUALPRODUCTPRESSTATUS {

        @XmlElement(name = "INFO")
        protected List<InfoType> info;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InfoType }
         * 
         * 
         */
        public List<InfoType> getINFO() {
            if (info == null) {
                info = new ArrayList<InfoType>();
            }
            return this.info;
        }

    }

}
