//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.lookup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.fhir.transform.xml.dmd.v2_3.lookup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.fhir.transform.xml.dmd.v2_3.lookup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LOOKUP }
     * 
     */
    public LOOKUP createLOOKUP() {
        return new LOOKUP();
    }

    /**
     * Create an instance of {@link LOOKUP.COMBINATIONPACKIND }
     * 
     */
    public LOOKUP.COMBINATIONPACKIND createLOOKUPCOMBINATIONPACKIND() {
        return new LOOKUP.COMBINATIONPACKIND();
    }

    /**
     * Create an instance of {@link LOOKUP.COMBINATIONPRODIND }
     * 
     */
    public LOOKUP.COMBINATIONPRODIND createLOOKUPCOMBINATIONPRODIND() {
        return new LOOKUP.COMBINATIONPRODIND();
    }

    /**
     * Create an instance of {@link LOOKUP.BASISOFNAME }
     * 
     */
    public LOOKUP.BASISOFNAME createLOOKUPBASISOFNAME() {
        return new LOOKUP.BASISOFNAME();
    }

    /**
     * Create an instance of {@link LOOKUP.NAMECHANGEREASON }
     * 
     */
    public LOOKUP.NAMECHANGEREASON createLOOKUPNAMECHANGEREASON() {
        return new LOOKUP.NAMECHANGEREASON();
    }

    /**
     * Create an instance of {@link LOOKUP.VIRTUALPRODUCTPRESSTATUS }
     * 
     */
    public LOOKUP.VIRTUALPRODUCTPRESSTATUS createLOOKUPVIRTUALPRODUCTPRESSTATUS() {
        return new LOOKUP.VIRTUALPRODUCTPRESSTATUS();
    }

    /**
     * Create an instance of {@link LOOKUP.CONTROLDRUGCATEGORY }
     * 
     */
    public LOOKUP.CONTROLDRUGCATEGORY createLOOKUPCONTROLDRUGCATEGORY() {
        return new LOOKUP.CONTROLDRUGCATEGORY();
    }

    /**
     * Create an instance of {@link LOOKUP.LICENSINGAUTHORITY }
     * 
     */
    public LOOKUP.LICENSINGAUTHORITY createLOOKUPLICENSINGAUTHORITY() {
        return new LOOKUP.LICENSINGAUTHORITY();
    }

    /**
     * Create an instance of {@link LOOKUP.UNITOFMEASURE }
     * 
     */
    public LOOKUP.UNITOFMEASURE createLOOKUPUNITOFMEASURE() {
        return new LOOKUP.UNITOFMEASURE();
    }

    /**
     * Create an instance of {@link LOOKUP.FORM }
     * 
     */
    public LOOKUP.FORM createLOOKUPFORM() {
        return new LOOKUP.FORM();
    }

    /**
     * Create an instance of {@link LOOKUP.ONTFORMROUTE }
     * 
     */
    public LOOKUP.ONTFORMROUTE createLOOKUPONTFORMROUTE() {
        return new LOOKUP.ONTFORMROUTE();
    }

    /**
     * Create an instance of {@link LOOKUP.ROUTE }
     * 
     */
    public LOOKUP.ROUTE createLOOKUPROUTE() {
        return new LOOKUP.ROUTE();
    }

    /**
     * Create an instance of {@link LOOKUP.DTPAYMENTCATEGORY }
     * 
     */
    public LOOKUP.DTPAYMENTCATEGORY createLOOKUPDTPAYMENTCATEGORY() {
        return new LOOKUP.DTPAYMENTCATEGORY();
    }

    /**
     * Create an instance of {@link LOOKUP.SUPPLIER }
     * 
     */
    public LOOKUP.SUPPLIER createLOOKUPSUPPLIER() {
        return new LOOKUP.SUPPLIER();
    }

    /**
     * Create an instance of {@link LOOKUP.FLAVOUR }
     * 
     */
    public LOOKUP.FLAVOUR createLOOKUPFLAVOUR() {
        return new LOOKUP.FLAVOUR();
    }

    /**
     * Create an instance of {@link LOOKUP.COLOUR }
     * 
     */
    public LOOKUP.COLOUR createLOOKUPCOLOUR() {
        return new LOOKUP.COLOUR();
    }

    /**
     * Create an instance of {@link LOOKUP.BASISOFSTRNTH }
     * 
     */
    public LOOKUP.BASISOFSTRNTH createLOOKUPBASISOFSTRNTH() {
        return new LOOKUP.BASISOFSTRNTH();
    }

    /**
     * Create an instance of {@link LOOKUP.REIMBURSEMENTSTATUS }
     * 
     */
    public LOOKUP.REIMBURSEMENTSTATUS createLOOKUPREIMBURSEMENTSTATUS() {
        return new LOOKUP.REIMBURSEMENTSTATUS();
    }

    /**
     * Create an instance of {@link LOOKUP.SPECCONT }
     * 
     */
    public LOOKUP.SPECCONT createLOOKUPSPECCONT() {
        return new LOOKUP.SPECCONT();
    }

    /**
     * Create an instance of {@link LOOKUP.DND }
     * 
     */
    public LOOKUP.DND createLOOKUPDND() {
        return new LOOKUP.DND();
    }

    /**
     * Create an instance of {@link LOOKUP.VIRTUALPRODUCTNONAVAIL }
     * 
     */
    public LOOKUP.VIRTUALPRODUCTNONAVAIL createLOOKUPVIRTUALPRODUCTNONAVAIL() {
        return new LOOKUP.VIRTUALPRODUCTNONAVAIL();
    }

    /**
     * Create an instance of {@link LOOKUP.DISCONTINUEDIND }
     * 
     */
    public LOOKUP.DISCONTINUEDIND createLOOKUPDISCONTINUEDIND() {
        return new LOOKUP.DISCONTINUEDIND();
    }

    /**
     * Create an instance of {@link LOOKUP.DFINDICATOR }
     * 
     */
    public LOOKUP.DFINDICATOR createLOOKUPDFINDICATOR() {
        return new LOOKUP.DFINDICATOR();
    }

    /**
     * Create an instance of {@link LOOKUP.PRICEBASIS }
     * 
     */
    public LOOKUP.PRICEBASIS createLOOKUPPRICEBASIS() {
        return new LOOKUP.PRICEBASIS();
    }

    /**
     * Create an instance of {@link LOOKUP.LEGALCATEGORY }
     * 
     */
    public LOOKUP.LEGALCATEGORY createLOOKUPLEGALCATEGORY() {
        return new LOOKUP.LEGALCATEGORY();
    }

    /**
     * Create an instance of {@link LOOKUP.AVAILABILITYRESTRICTION }
     * 
     */
    public LOOKUP.AVAILABILITYRESTRICTION createLOOKUPAVAILABILITYRESTRICTION() {
        return new LOOKUP.AVAILABILITYRESTRICTION();
    }

    /**
     * Create an instance of {@link LOOKUP.LICENSINGAUTHORITYCHANGEREASON }
     * 
     */
    public LOOKUP.LICENSINGAUTHORITYCHANGEREASON createLOOKUPLICENSINGAUTHORITYCHANGEREASON() {
        return new LOOKUP.LICENSINGAUTHORITYCHANGEREASON();
    }

    /**
     * Create an instance of {@link InfoType }
     * 
     */
    public InfoType createInfoType() {
        return new InfoType();
    }

    /**
     * Create an instance of {@link HistoryInfoType }
     * 
     */
    public HistoryInfoType createHistoryInfoType() {
        return new HistoryInfoType();
    }

    /**
     * Create an instance of {@link SupplierInfoType }
     * 
     */
    public SupplierInfoType createSupplierInfoType() {
        return new SupplierInfoType();
    }

}
