//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.amp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApiType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="APID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="ISID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="STRNTH" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="UOMCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApiType", propOrder = {

})
public class ApiType {

    @XmlElement(name = "APID", required = true)
    protected BigInteger apid;
    @XmlElement(name = "ISID", required = true)
    protected BigInteger isid;
    @XmlElement(name = "STRNTH")
    protected Float strnth;
    @XmlElement(name = "UOMCD")
    protected BigInteger uomcd;

    /**
     * Gets the value of the apid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAPID() {
        return apid;
    }

    /**
     * Sets the value of the apid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAPID(BigInteger value) {
        this.apid = value;
    }

    /**
     * Gets the value of the isid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getISID() {
        return isid;
    }

    /**
     * Sets the value of the isid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setISID(BigInteger value) {
        this.isid = value;
    }

    /**
     * Gets the value of the strnth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSTRNTH() {
        return strnth;
    }

    /**
     * Sets the value of the strnth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSTRNTH(Float value) {
        this.strnth = value;
    }

    /**
     * Gets the value of the uomcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUOMCD() {
        return uomcd;
    }

    /**
     * Sets the value of the uomcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUOMCD(BigInteger value) {
        this.uomcd = value;
    }

}
