//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.amp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppProdInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppProdInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="APID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="SZ_WEIGHT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="COLOURCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="PROD_ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppProdInfoType", propOrder = {

})
public class AppProdInfoType {

    @XmlElement(name = "APID", required = true)
    protected BigInteger apid;
    @XmlElement(name = "SZ_WEIGHT")
    protected String szweight;
    @XmlElement(name = "COLOURCD")
    protected BigInteger colourcd;
    @XmlElement(name = "PROD_ORDER_NO")
    protected String prodorderno;

    /**
     * Gets the value of the apid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAPID() {
        return apid;
    }

    /**
     * Sets the value of the apid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAPID(BigInteger value) {
        this.apid = value;
    }

    /**
     * Gets the value of the szweight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSZWEIGHT() {
        return szweight;
    }

    /**
     * Sets the value of the szweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSZWEIGHT(String value) {
        this.szweight = value;
    }

    /**
     * Gets the value of the colourcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOLOURCD() {
        return colourcd;
    }

    /**
     * Sets the value of the colourcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOLOURCD(BigInteger value) {
        this.colourcd = value;
    }

    /**
     * Gets the value of the prodorderno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODORDERNO() {
        return prodorderno;
    }

    /**
     * Sets the value of the prodorderno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODORDERNO(String value) {
        this.prodorderno = value;
    }

}
