//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//

package au.csiro.fhir.transforms.xml.dmd.v2_3.bnf;

import javax.xml.bind.annotation.XmlRegistry;

import au.csiro.fhir.transforms.xml.dmd.v2_3.vmp.VIRTUALMEDPRODUCTS;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.fhir.transform.xml.dmd.v2_3.vmp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class BNFObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.fhir.transform.xml.dmd.v2_3.vmp
     * 
     */
    public BNFObjectFactory() {
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS }
     * 
     */
    public BNFS createBNFS() {
        return new BNFS();
    }

    /**
     * Create an instance of {@link BNFS.VMPS }
     * 
     */
    public BNFS.VMPS createBNFVMPS() {
        return new BNFS.VMPS();
    }

    /**
     * Create an instance of {@link BnfVmpType }
     * 
     */
    public BnfVmpType createBnfVmpType() {
        return new BnfVmpType();
    }

        /**
     * Create an instance of {@link BNFS.VMPS }
     * 
     */
    public BNFS.AMPS createBNFAMPS() {
        return new BNFS.AMPS();
    }

    /**
     * Create an instance of {@link BnfAmpType }
     * 
     */
    public BnfAmpType createBnfAmpType() {
        return new BnfAmpType();
    }
}
