//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.ampp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AmppType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AmppType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="APPID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="INVALID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ABBREVNM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VPPID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="APID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="COMBPACKCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="LEGAL_CATCD" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="SUBP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DISCCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="DISCDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmppType", propOrder = {

})
public class AmppType {

    @XmlElement(name = "APPID", required = true)
    protected BigInteger appid;
    @XmlElement(name = "INVALID")
    protected BigInteger invalid;
    @XmlElement(name = "NM", required = true)
    protected String nm;
    @XmlElement(name = "ABBREVNM")
    protected String abbrevnm;
    @XmlElement(name = "VPPID", required = true)
    protected BigInteger vppid;
    @XmlElement(name = "APID", required = true)
    protected BigInteger apid;
    @XmlElement(name = "COMBPACKCD")
    protected BigInteger combpackcd;
    @XmlElement(name = "LEGAL_CATCD", required = true)
    protected BigInteger legalcatcd;
    @XmlElement(name = "SUBP")
    protected String subp;
    @XmlElement(name = "DISCCD")
    protected BigInteger disccd;
    @XmlElement(name = "DISCDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar discdt;

    /**
     * Gets the value of the appid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAPPID() {
        return appid;
    }

    /**
     * Sets the value of the appid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAPPID(BigInteger value) {
        this.appid = value;
    }

    /**
     * Gets the value of the invalid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getINVALID() {
        return invalid;
    }

    /**
     * Sets the value of the invalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setINVALID(BigInteger value) {
        this.invalid = value;
    }

    /**
     * Gets the value of the nm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNM() {
        return nm;
    }

    /**
     * Sets the value of the nm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNM(String value) {
        this.nm = value;
    }

    /**
     * Gets the value of the abbrevnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABBREVNM() {
        return abbrevnm;
    }

    /**
     * Sets the value of the abbrevnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABBREVNM(String value) {
        this.abbrevnm = value;
    }

    /**
     * Gets the value of the vppid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVPPID() {
        return vppid;
    }

    /**
     * Sets the value of the vppid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVPPID(BigInteger value) {
        this.vppid = value;
    }

    /**
     * Gets the value of the apid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAPID() {
        return apid;
    }

    /**
     * Sets the value of the apid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAPID(BigInteger value) {
        this.apid = value;
    }

    /**
     * Gets the value of the combpackcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOMBPACKCD() {
        return combpackcd;
    }

    /**
     * Sets the value of the combpackcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOMBPACKCD(BigInteger value) {
        this.combpackcd = value;
    }

    /**
     * Gets the value of the legalcatcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLEGALCATCD() {
        return legalcatcd;
    }

    /**
     * Sets the value of the legalcatcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLEGALCATCD(BigInteger value) {
        this.legalcatcd = value;
    }

    /**
     * Gets the value of the subp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBP() {
        return subp;
    }

    /**
     * Sets the value of the subp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBP(String value) {
        this.subp = value;
    }

    /**
     * Gets the value of the disccd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDISCCD() {
        return disccd;
    }

    /**
     * Sets the value of the disccd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDISCCD(BigInteger value) {
        this.disccd = value;
    }

    /**
     * Gets the value of the discdt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDISCDT() {
        return discdt;
    }

    /**
     * Sets the value of the discdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDISCDT(XMLGregorianCalendar value) {
        this.discdt = value;
    }

}
