//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.ampp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.fhir.transform.xml.dmd.v2_3.ampp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.fhir.transform.xml.dmd.v2_3.ampp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODPACKS }
     * 
     */
    public ACTUALMEDICINALPRODPACKS createACTUALMEDICINALPRODPACKS() {
        return new ACTUALMEDICINALPRODPACKS();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODPACKS.AMPPS }
     * 
     */
    public ACTUALMEDICINALPRODPACKS.AMPPS createACTUALMEDICINALPRODPACKSAMPPS() {
        return new ACTUALMEDICINALPRODPACKS.AMPPS();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODPACKS.APPLIANCEPACKINFO }
     * 
     */
    public ACTUALMEDICINALPRODPACKS.APPLIANCEPACKINFO createACTUALMEDICINALPRODPACKSAPPLIANCEPACKINFO() {
        return new ACTUALMEDICINALPRODPACKS.APPLIANCEPACKINFO();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODPACKS.DRUGPRODUCTPRESCRIBINFO }
     * 
     */
    public ACTUALMEDICINALPRODPACKS.DRUGPRODUCTPRESCRIBINFO createACTUALMEDICINALPRODPACKSDRUGPRODUCTPRESCRIBINFO() {
        return new ACTUALMEDICINALPRODPACKS.DRUGPRODUCTPRESCRIBINFO();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODPACKS.MEDICINALPRODUCTPRICE }
     * 
     */
    public ACTUALMEDICINALPRODPACKS.MEDICINALPRODUCTPRICE createACTUALMEDICINALPRODPACKSMEDICINALPRODUCTPRICE() {
        return new ACTUALMEDICINALPRODPACKS.MEDICINALPRODUCTPRICE();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODPACKS.REIMBURSEMENTINFO }
     * 
     */
    public ACTUALMEDICINALPRODPACKS.REIMBURSEMENTINFO createACTUALMEDICINALPRODPACKSREIMBURSEMENTINFO() {
        return new ACTUALMEDICINALPRODPACKS.REIMBURSEMENTINFO();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODPACKS.COMBCONTENT }
     * 
     */
    public ACTUALMEDICINALPRODPACKS.COMBCONTENT createACTUALMEDICINALPRODPACKSCOMBCONTENT() {
        return new ACTUALMEDICINALPRODPACKS.COMBCONTENT();
    }

    /**
     * Create an instance of {@link AmppType }
     * 
     */
    public AmppType createAmppType() {
        return new AmppType();
    }

    /**
     * Create an instance of {@link PackInfoType }
     * 
     */
    public PackInfoType createPackInfoType() {
        return new PackInfoType();
    }

    /**
     * Create an instance of {@link PrescInfoType }
     * 
     */
    public PrescInfoType createPrescInfoType() {
        return new PrescInfoType();
    }

    /**
     * Create an instance of {@link PriceInfoType }
     * 
     */
    public PriceInfoType createPriceInfoType() {
        return new PriceInfoType();
    }

    /**
     * Create an instance of {@link ReimbInfoType }
     * 
     */
    public ReimbInfoType createReimbInfoType() {
        return new ReimbInfoType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

}
