//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.ampp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PackInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="APPID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="REIMB_STATCD" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="REIMB_STATDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="REIMB_STATPREVCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="PACK_ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackInfoType", propOrder = {

})
public class PackInfoType {

    @XmlElement(name = "APPID", required = true)
    protected BigInteger appid;
    @XmlElement(name = "REIMB_STATCD", required = true)
    protected BigInteger reimbstatcd;
    @XmlElement(name = "REIMB_STATDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reimbstatdt;
    @XmlElement(name = "REIMB_STATPREVCD")
    protected BigInteger reimbstatprevcd;
    @XmlElement(name = "PACK_ORDER_NO")
    protected String packorderno;

    /**
     * Gets the value of the appid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAPPID() {
        return appid;
    }

    /**
     * Sets the value of the appid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAPPID(BigInteger value) {
        this.appid = value;
    }

    /**
     * Gets the value of the reimbstatcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREIMBSTATCD() {
        return reimbstatcd;
    }

    /**
     * Sets the value of the reimbstatcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREIMBSTATCD(BigInteger value) {
        this.reimbstatcd = value;
    }

    /**
     * Gets the value of the reimbstatdt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getREIMBSTATDT() {
        return reimbstatdt;
    }

    /**
     * Sets the value of the reimbstatdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setREIMBSTATDT(XMLGregorianCalendar value) {
        this.reimbstatdt = value;
    }

    /**
     * Gets the value of the reimbstatprevcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREIMBSTATPREVCD() {
        return reimbstatprevcd;
    }

    /**
     * Sets the value of the reimbstatprevcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREIMBSTATPREVCD(BigInteger value) {
        this.reimbstatprevcd = value;
    }

    /**
     * Gets the value of the packorderno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACKORDERNO() {
        return packorderno;
    }

    /**
     * Sets the value of the packorderno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACKORDERNO(String value) {
        this.packorderno = value;
    }

}
