//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.ampp;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrescInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrescInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="APPID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="SCHED_2" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="ACBS" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="PADM" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="FP10_MDA" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="SCHED_1" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="HOSP" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NURSE_F" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="ENURSE_F" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="DENT_F" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrescInfoType", propOrder = {

})
public class PrescInfoType {

    @XmlElement(name = "APPID", required = true)
    protected BigInteger appid;
    @XmlElement(name = "SCHED_2")
    protected BigInteger sched2;
    @XmlElement(name = "ACBS")
    protected BigInteger acbs;
    @XmlElement(name = "PADM")
    protected BigInteger padm;
    @XmlElement(name = "FP10_MDA")
    protected BigInteger fp10MDA;
    @XmlElement(name = "SCHED_1")
    protected BigInteger sched1;
    @XmlElement(name = "HOSP")
    protected BigInteger hosp;
    @XmlElement(name = "NURSE_F")
    protected BigInteger nursef;
    @XmlElement(name = "ENURSE_F")
    protected BigInteger enursef;
    @XmlElement(name = "DENT_F")
    protected BigInteger dentf;

    /**
     * Gets the value of the appid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAPPID() {
        return appid;
    }

    /**
     * Sets the value of the appid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAPPID(BigInteger value) {
        this.appid = value;
    }

    /**
     * Gets the value of the sched2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSCHED2() {
        return sched2;
    }

    /**
     * Sets the value of the sched2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSCHED2(BigInteger value) {
        this.sched2 = value;
    }

    /**
     * Gets the value of the acbs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getACBS() {
        return acbs;
    }

    /**
     * Sets the value of the acbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setACBS(BigInteger value) {
        this.acbs = value;
    }

    /**
     * Gets the value of the padm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPADM() {
        return padm;
    }

    /**
     * Sets the value of the padm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPADM(BigInteger value) {
        this.padm = value;
    }

    /**
     * Gets the value of the fp10MDA property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFP10MDA() {
        return fp10MDA;
    }

    /**
     * Sets the value of the fp10MDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFP10MDA(BigInteger value) {
        this.fp10MDA = value;
    }

    /**
     * Gets the value of the sched1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSCHED1() {
        return sched1;
    }

    /**
     * Sets the value of the sched1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSCHED1(BigInteger value) {
        this.sched1 = value;
    }

    /**
     * Gets the value of the hosp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHOSP() {
        return hosp;
    }

    /**
     * Sets the value of the hosp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHOSP(BigInteger value) {
        this.hosp = value;
    }

    /**
     * Gets the value of the nursef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNURSEF() {
        return nursef;
    }

    /**
     * Sets the value of the nursef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNURSEF(BigInteger value) {
        this.nursef = value;
    }

    /**
     * Gets the value of the enursef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getENURSEF() {
        return enursef;
    }

    /**
     * Sets the value of the enursef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setENURSEF(BigInteger value) {
        this.enursef = value;
    }

    /**
     * Gets the value of the dentf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDENTF() {
        return dentf;
    }

    /**
     * Sets the value of the dentf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDENTF(BigInteger value) {
        this.dentf = value;
    }

}
