//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.ampp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReimbInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReimbInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="APPID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="PX_CHRGS" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="DISP_FEES" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="BB" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="LTD_STAB" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="CAL_PACK" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="SPEC_CONTCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="DND" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="FP34D" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReimbInfoType", propOrder = {

})
public class ReimbInfoType {

    @XmlElement(name = "APPID", required = true)
    protected BigInteger appid;
    @XmlElement(name = "PX_CHRGS")
    protected BigInteger pxchrgs;
    @XmlElement(name = "DISP_FEES")
    protected BigInteger dispfees;
    @XmlElement(name = "BB")
    protected BigInteger bb;
    @XmlElement(name = "LTD_STAB")
    protected BigInteger ltdstab;
    @XmlElement(name = "CAL_PACK")
    protected BigInteger calpack;
    @XmlElement(name = "SPEC_CONTCD")
    protected BigInteger speccontcd;
    @XmlElement(name = "DND")
    protected BigInteger dnd;
    @XmlElement(name = "FP34D")
    protected BigInteger fp34D;

    /**
     * Gets the value of the appid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAPPID() {
        return appid;
    }

    /**
     * Sets the value of the appid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAPPID(BigInteger value) {
        this.appid = value;
    }

    /**
     * Gets the value of the pxchrgs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPXCHRGS() {
        return pxchrgs;
    }

    /**
     * Sets the value of the pxchrgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPXCHRGS(BigInteger value) {
        this.pxchrgs = value;
    }

    /**
     * Gets the value of the dispfees property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDISPFEES() {
        return dispfees;
    }

    /**
     * Sets the value of the dispfees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDISPFEES(BigInteger value) {
        this.dispfees = value;
    }

    /**
     * Gets the value of the bb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBB() {
        return bb;
    }

    /**
     * Sets the value of the bb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBB(BigInteger value) {
        this.bb = value;
    }

    /**
     * Gets the value of the ltdstab property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLTDSTAB() {
        return ltdstab;
    }

    /**
     * Sets the value of the ltdstab property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLTDSTAB(BigInteger value) {
        this.ltdstab = value;
    }

    /**
     * Gets the value of the calpack property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCALPACK() {
        return calpack;
    }

    /**
     * Sets the value of the calpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCALPACK(BigInteger value) {
        this.calpack = value;
    }

    /**
     * Gets the value of the speccontcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSPECCONTCD() {
        return speccontcd;
    }

    /**
     * Sets the value of the speccontcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSPECCONTCD(BigInteger value) {
        this.speccontcd = value;
    }

    /**
     * Gets the value of the dnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDND() {
        return dnd;
    }

    /**
     * Sets the value of the dnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDND(BigInteger value) {
        this.dnd = value;
    }

    /**
     * Gets the value of the fp34D property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFP34D() {
        return fp34D;
    }

    /**
     * Sets the value of the fp34D property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFP34D(BigInteger value) {
        this.fp34D = value;
    }

}
