//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.vmpp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.fhir.transform.xml.dmd.v2_3.vmpp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.fhir.transform.xml.dmd.v2_3.vmpp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTPACK }
     * 
     */
    public VIRTUALMEDPRODUCTPACK createVIRTUALMEDPRODUCTPACK() {
        return new VIRTUALMEDPRODUCTPACK();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTPACK.VMPPS }
     * 
     */
    public VIRTUALMEDPRODUCTPACK.VMPPS createVIRTUALMEDPRODUCTPACKVMPPS() {
        return new VIRTUALMEDPRODUCTPACK.VMPPS();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO }
     * 
     */
    public VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO createVIRTUALMEDPRODUCTPACKDRUGTARIFFINFO() {
        return new VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTPACK.COMBCONTENT }
     * 
     */
    public VIRTUALMEDPRODUCTPACK.COMBCONTENT createVIRTUALMEDPRODUCTPACKCOMBCONTENT() {
        return new VIRTUALMEDPRODUCTPACK.COMBCONTENT();
    }

    /**
     * Create an instance of {@link VmppType }
     * 
     */
    public VmppType createVmppType() {
        return new VmppType();
    }

    /**
     * Create an instance of {@link DtInfoType }
     * 
     */
    public DtInfoType createDtInfoType() {
        return new DtInfoType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

}
