//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.vmpp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VMPPS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VMPP" type="{}VmppType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DRUG_TARIFF_INFO"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DTINFO" type="{}DtInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="COMB_CONTENT"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CCONTENT" type="{}ContentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vmpps",
    "drugtariffinfo",
    "combcontent"
})
@XmlRootElement(name = "VIRTUAL_MED_PRODUCT_PACK")
public class VIRTUALMEDPRODUCTPACK {

    @XmlElement(name = "VMPPS", required = true)
    protected VIRTUALMEDPRODUCTPACK.VMPPS vmpps;
    @XmlElement(name = "DRUG_TARIFF_INFO", required = true)
    protected VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO drugtariffinfo;
    @XmlElement(name = "COMB_CONTENT", required = true)
    protected VIRTUALMEDPRODUCTPACK.COMBCONTENT combcontent;

    /**
     * Gets the value of the vmpps property.
     * 
     * @return
     *     possible object is
     *     {@link VIRTUALMEDPRODUCTPACK.VMPPS }
     *     
     */
    public VIRTUALMEDPRODUCTPACK.VMPPS getVMPPS() {
        return vmpps;
    }

    /**
     * Sets the value of the vmpps property.
     * 
     * @param value
     *     allowed object is
     *     {@link VIRTUALMEDPRODUCTPACK.VMPPS }
     *     
     */
    public void setVMPPS(VIRTUALMEDPRODUCTPACK.VMPPS value) {
        this.vmpps = value;
    }

    /**
     * Gets the value of the drugtariffinfo property.
     * 
     * @return
     *     possible object is
     *     {@link VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO }
     *     
     */
    public VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO getDRUGTARIFFINFO() {
        return drugtariffinfo;
    }

    /**
     * Sets the value of the drugtariffinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO }
     *     
     */
    public void setDRUGTARIFFINFO(VIRTUALMEDPRODUCTPACK.DRUGTARIFFINFO value) {
        this.drugtariffinfo = value;
    }

    /**
     * Gets the value of the combcontent property.
     * 
     * @return
     *     possible object is
     *     {@link VIRTUALMEDPRODUCTPACK.COMBCONTENT }
     *     
     */
    public VIRTUALMEDPRODUCTPACK.COMBCONTENT getCOMBCONTENT() {
        return combcontent;
    }

    /**
     * Sets the value of the combcontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link VIRTUALMEDPRODUCTPACK.COMBCONTENT }
     *     
     */
    public void setCOMBCONTENT(VIRTUALMEDPRODUCTPACK.COMBCONTENT value) {
        this.combcontent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CCONTENT" type="{}ContentType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ccontent"
    })
    public static class COMBCONTENT {

        @XmlElement(name = "CCONTENT")
        protected List<ContentType> ccontent;

        /**
         * Gets the value of the ccontent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ccontent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCCONTENT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ContentType }
         * 
         * 
         */
        public List<ContentType> getCCONTENT() {
            if (ccontent == null) {
                ccontent = new ArrayList<ContentType>();
            }
            return this.ccontent;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DTINFO" type="{}DtInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dtinfo"
    })
    public static class DRUGTARIFFINFO {

        @XmlElement(name = "DTINFO")
        protected List<DtInfoType> dtinfo;

        /**
         * Gets the value of the dtinfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dtinfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDTINFO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DtInfoType }
         * 
         * 
         */
        public List<DtInfoType> getDTINFO() {
            if (dtinfo == null) {
                dtinfo = new ArrayList<DtInfoType>();
            }
            return this.dtinfo;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VMPP" type="{}VmppType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vmpp"
    })
    public static class VMPPS {

        @XmlElement(name = "VMPP")
        protected List<VmppType> vmpp;

        /**
         * Gets the value of the vmpp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vmpp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVMPP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VmppType }
         * 
         * 
         */
        public List<VmppType> getVMPP() {
            if (vmpp == null) {
                vmpp = new ArrayList<VmppType>();
            }
            return this.vmpp;
        }

    }

}
