//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.13 at 06:08:06 PM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.gtin;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GTINType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GTINType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;element name="GTIN" type="{}GTINCode"/&gt;
 *         &lt;element name="STARTDT" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ENDDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GTINType", propOrder = {
    "gtinAndSTARTDTAndENDDT"
})
public class GTINType {

    @XmlElementRefs({
        @XmlElementRef(name = "GTIN", type = JAXBElement.class),
        @XmlElementRef(name = "STARTDT", type = JAXBElement.class),
        @XmlElementRef(name = "ENDDT", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> gtinAndSTARTDTAndENDDT;

    /**
     * Gets the value of the gtinAndSTARTDTAndENDDT property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gtinAndSTARTDTAndENDDT property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGTINAndSTARTDTAndENDDT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getGTINAndSTARTDTAndENDDT() {
        if (gtinAndSTARTDTAndENDDT == null) {
            gtinAndSTARTDTAndENDDT = new ArrayList<JAXBElement<?>>();
        }
        return this.gtinAndSTARTDTAndENDDT;
    }

}
