//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 11:16:44 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.gtin;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GTINTypeGTIN_QNAME = new QName("", "GTIN");
    private final static QName _GTINTypeSTARTDT_QNAME = new QName("", "STARTDT");
    private final static QName _GTINTypeENDDT_QNAME = new QName("", "ENDDT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GTINDETAILS }
     * 
     */
    public GTINDETAILS createGTINDETAILS() {
        return new GTINDETAILS();
    }

    /**
     * Create an instance of {@link GTINDETAILS.AMPPS }
     * 
     */
    public GTINDETAILS.AMPPS createGTINDETAILSAMPPS() {
        return new GTINDETAILS.AMPPS();
    }

    /**
     * Create an instance of {@link AMPPType }
     * 
     */
    public AMPPType createAMPPType() {
        return new AMPPType();
    }

    /**
     * Create an instance of {@link GTINType }
     * 
     */
    public GTINType createGTINType() {
        return new GTINType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "GTIN", scope = GTINType.class)
    public JAXBElement<String> createGTINTypeGTIN(String value) {
        return new JAXBElement<String>(_GTINTypeGTIN_QNAME, String.class, GTINType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "STARTDT", scope = GTINType.class)
    public JAXBElement<XMLGregorianCalendar> createGTINTypeSTARTDT(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_GTINTypeSTARTDT_QNAME, XMLGregorianCalendar.class, GTINType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ENDDT", scope = GTINType.class)
    public JAXBElement<XMLGregorianCalendar> createGTINTypeENDDT(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_GTINTypeENDDT_QNAME, XMLGregorianCalendar.class, GTINType.class, value);
    }

}
