//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.vtm;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VTM" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VTMID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="INVALID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="NM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ABBREVNM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="VTMIDPREV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="VTMIDDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vtm"
})
@XmlRootElement(name = "VIRTUAL_THERAPEUTIC_MOIETIES")
public class VIRTUALTHERAPEUTICMOIETIES {

    @XmlElement(name = "VTM")
    protected List<VIRTUALTHERAPEUTICMOIETIES.VTM> vtm;

    /**
     * Gets the value of the vtm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vtm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVTM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VIRTUALTHERAPEUTICMOIETIES.VTM }
     * 
     * 
     */
    public List<VIRTUALTHERAPEUTICMOIETIES.VTM> getVTM() {
        if (vtm == null) {
            vtm = new ArrayList<VIRTUALTHERAPEUTICMOIETIES.VTM>();
        }
        return this.vtm;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VTMID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="INVALID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="NM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ABBREVNM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="VTMIDPREV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="VTMIDDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vtmid",
        "invalid",
        "nm",
        "abbrevnm",
        "vtmidprev",
        "vtmiddt"
    })
    public static class VTM {

        @XmlElement(name = "VTMID", required = true)
        protected BigInteger vtmid;
        @XmlElement(name = "INVALID")
        protected BigInteger invalid;
        @XmlElement(name = "NM", required = true)
        protected String nm;
        @XmlElement(name = "ABBREVNM")
        protected String abbrevnm;
        @XmlElement(name = "VTMIDPREV")
        protected String vtmidprev;
        @XmlElement(name = "VTMIDDT")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar vtmiddt;

        /**
         * Gets the value of the vtmid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVTMID() {
            return vtmid;
        }

        /**
         * Sets the value of the vtmid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVTMID(BigInteger value) {
            this.vtmid = value;
        }

        /**
         * Gets the value of the invalid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getINVALID() {
            return invalid;
        }

        /**
         * Sets the value of the invalid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setINVALID(BigInteger value) {
            this.invalid = value;
        }

        /**
         * Gets the value of the nm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNM() {
            return nm;
        }

        /**
         * Sets the value of the nm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNM(String value) {
            this.nm = value;
        }

        /**
         * Gets the value of the abbrevnm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getABBREVNM() {
            return abbrevnm;
        }

        /**
         * Sets the value of the abbrevnm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setABBREVNM(String value) {
            this.abbrevnm = value;
        }

        /**
         * Gets the value of the vtmidprev property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVTMIDPREV() {
            return vtmidprev;
        }

        /**
         * Sets the value of the vtmidprev property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVTMIDPREV(String value) {
            this.vtmidprev = value;
        }

        /**
         * Gets the value of the vtmiddt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getVTMIDDT() {
            return vtmiddt;
        }

        /**
         * Sets the value of the vtmiddt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setVTMIDDT(XMLGregorianCalendar value) {
            this.vtmiddt = value;
        }

    }

}
