//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.15 at 09:35:02 AM AEDT 
//


package au.csiro.fhir.transforms.xml.dmd.tradefamily.v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TRADEFAMILY }
     * 
     */
    public TRADEFAMILY createTRADEFAMILY() {
        return new TRADEFAMILY();
    }

    /**
     * Create an instance of {@link TRADEFAMILY.TFS }
     * 
     */
    public TRADEFAMILY.TFS createTRADEFAMILYTFS() {
        return new TRADEFAMILY.TFS();
    }

    /**
     * Create an instance of {@link TRADEFAMILY.TFGS }
     * 
     */
    public TRADEFAMILY.TFGS createTRADEFAMILYTFGS() {
        return new TRADEFAMILY.TFGS();
    }

    /**
     * Create an instance of {@link TRADEFAMILY.TFAMPS }
     * 
     */
    public TRADEFAMILY.TFAMPS createTRADEFAMILYTFAMPS() {
        return new TRADEFAMILY.TFAMPS();
    }

    /**
     * Create an instance of {@link TFType }
     * 
     */
    public TFType createTFType() {
        return new TFType();
    }

    /**
     * Create an instance of {@link TFGType }
     * 
     */
    public TFGType createTFGType() {
        return new TFGType();
    }

    /**
     * Create an instance of {@link TFAMPType }
     * 
     */
    public TFAMPType createTFAMPType() {
        return new TFAMPType();
    }

}
