//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.15 at 09:35:02 AM AEDT 
//


package au.csiro.fhir.transforms.xml.dmd.tradefamily.v1_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TFGType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TFGType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="TFGID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="TFGIDDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="TFGIDPREV" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="INVALID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NMDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="NMPREV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TFGType", propOrder = {

})
public class TFGType {

    @XmlElement(name = "TFGID", required = true)
    protected BigInteger tfgid;
    @XmlElement(name = "TFGIDDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tfgiddt;
    @XmlElement(name = "TFGIDPREV")
    protected BigInteger tfgidprev;
    @XmlElement(name = "INVALID")
    protected BigInteger invalid;
    @XmlElement(name = "NM", required = true)
    protected String nm;
    @XmlElement(name = "NMDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nmdt;
    @XmlElement(name = "NMPREV")
    protected String nmprev;

    /**
     * Gets the value of the tfgid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTFGID() {
        return tfgid;
    }

    /**
     * Sets the value of the tfgid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTFGID(BigInteger value) {
        this.tfgid = value;
    }

    /**
     * Gets the value of the tfgiddt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTFGIDDT() {
        return tfgiddt;
    }

    /**
     * Sets the value of the tfgiddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTFGIDDT(XMLGregorianCalendar value) {
        this.tfgiddt = value;
    }

    /**
     * Gets the value of the tfgidprev property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTFGIDPREV() {
        return tfgidprev;
    }

    /**
     * Sets the value of the tfgidprev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTFGIDPREV(BigInteger value) {
        this.tfgidprev = value;
    }

    /**
     * Gets the value of the invalid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getINVALID() {
        return invalid;
    }

    /**
     * Sets the value of the invalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setINVALID(BigInteger value) {
        this.invalid = value;
    }

    /**
     * Gets the value of the nm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNM() {
        return nm;
    }

    /**
     * Sets the value of the nm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNM(String value) {
        this.nm = value;
    }

    /**
     * Gets the value of the nmdt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNMDT() {
        return nmdt;
    }

    /**
     * Sets the value of the nmdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNMDT(XMLGregorianCalendar value) {
        this.nmdt = value;
    }

    /**
     * Gets the value of the nmprev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMPREV() {
        return nmprev;
    }

    /**
     * Sets the value of the nmprev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMPREV(String value) {
        this.nmprev = value;
    }

}
