//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.15 at 09:35:02 AM AEDT 
//


package au.csiro.fhir.transforms.xml.dmd.tradefamily.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TFS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TF" type="{}TFType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TFGS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TFG" type="{}TFGType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TF_AMPS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TF_AMP" type="{}TFAMPType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tfs",
    "tfgs",
    "tfamps"
})
@XmlRootElement(name = "TRADE_FAMILY")
public class TRADEFAMILY {

    @XmlElement(name = "TFS", required = true)
    protected TRADEFAMILY.TFS tfs;
    @XmlElement(name = "TFGS", required = true)
    protected TRADEFAMILY.TFGS tfgs;
    @XmlElement(name = "TF_AMPS", required = true)
    protected TRADEFAMILY.TFAMPS tfamps;

    /**
     * Gets the value of the tfs property.
     * 
     * @return
     *     possible object is
     *     {@link TRADEFAMILY.TFS }
     *     
     */
    public TRADEFAMILY.TFS getTFS() {
        return tfs;
    }

    /**
     * Sets the value of the tfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRADEFAMILY.TFS }
     *     
     */
    public void setTFS(TRADEFAMILY.TFS value) {
        this.tfs = value;
    }

    /**
     * Gets the value of the tfgs property.
     * 
     * @return
     *     possible object is
     *     {@link TRADEFAMILY.TFGS }
     *     
     */
    public TRADEFAMILY.TFGS getTFGS() {
        return tfgs;
    }

    /**
     * Sets the value of the tfgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRADEFAMILY.TFGS }
     *     
     */
    public void setTFGS(TRADEFAMILY.TFGS value) {
        this.tfgs = value;
    }

    /**
     * Gets the value of the tfamps property.
     * 
     * @return
     *     possible object is
     *     {@link TRADEFAMILY.TFAMPS }
     *     
     */
    public TRADEFAMILY.TFAMPS getTFAMPS() {
        return tfamps;
    }

    /**
     * Sets the value of the tfamps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRADEFAMILY.TFAMPS }
     *     
     */
    public void setTFAMPS(TRADEFAMILY.TFAMPS value) {
        this.tfamps = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TF_AMP" type="{}TFAMPType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tfamp"
    })
    public static class TFAMPS {

        @XmlElement(name = "TF_AMP")
        protected List<TFAMPType> tfamp;

        /**
         * Gets the value of the tfamp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tfamp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTFAMP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TFAMPType }
         * 
         * 
         */
        public List<TFAMPType> getTFAMP() {
            if (tfamp == null) {
                tfamp = new ArrayList<TFAMPType>();
            }
            return this.tfamp;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TFG" type="{}TFGType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tfg"
    })
    public static class TFGS {

        @XmlElement(name = "TFG")
        protected List<TFGType> tfg;

        /**
         * Gets the value of the tfg property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tfg property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTFG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TFGType }
         * 
         * 
         */
        public List<TFGType> getTFG() {
            if (tfg == null) {
                tfg = new ArrayList<TFGType>();
            }
            return this.tfg;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TF" type="{}TFType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tf"
    })
    public static class TFS {

        @XmlElement(name = "TF")
        protected List<TFType> tf;

        /**
         * Gets the value of the tf property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tf property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TFType }
         * 
         * 
         */
        public List<TFType> getTF() {
            if (tf == null) {
                tf = new ArrayList<TFType>();
            }
            return this.tf;
        }

    }

}
