//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transform.xml.dmd.v2_3.amp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.fhir.transform.xml.dmd.v2_3.amp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.fhir.transform.xml.dmd.v2_3.amp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODUCTS }
     * 
     */
    public ACTUALMEDICINALPRODUCTS createACTUALMEDICINALPRODUCTS() {
        return new ACTUALMEDICINALPRODUCTS();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODUCTS.AMPS }
     * 
     */
    public ACTUALMEDICINALPRODUCTS.AMPS createACTUALMEDICINALPRODUCTSAMPS() {
        return new ACTUALMEDICINALPRODUCTS.AMPS();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODUCTS.APINGREDIENT }
     * 
     */
    public ACTUALMEDICINALPRODUCTS.APINGREDIENT createACTUALMEDICINALPRODUCTSAPINGREDIENT() {
        return new ACTUALMEDICINALPRODUCTS.APINGREDIENT();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODUCTS.LICENSEDROUTE }
     * 
     */
    public ACTUALMEDICINALPRODUCTS.LICENSEDROUTE createACTUALMEDICINALPRODUCTSLICENSEDROUTE() {
        return new ACTUALMEDICINALPRODUCTS.LICENSEDROUTE();
    }

    /**
     * Create an instance of {@link ACTUALMEDICINALPRODUCTS.APINFORMATION }
     * 
     */
    public ACTUALMEDICINALPRODUCTS.APINFORMATION createACTUALMEDICINALPRODUCTSAPINFORMATION() {
        return new ACTUALMEDICINALPRODUCTS.APINFORMATION();
    }

    /**
     * Create an instance of {@link AmpType }
     * 
     */
    public AmpType createAmpType() {
        return new AmpType();
    }

    /**
     * Create an instance of {@link ApiType }
     * 
     */
    public ApiType createApiType() {
        return new ApiType();
    }

    /**
     * Create an instance of {@link LicRouteType }
     * 
     */
    public LicRouteType createLicRouteType() {
        return new LicRouteType();
    }

    /**
     * Create an instance of {@link AppProdInfoType }
     * 
     */
    public AppProdInfoType createAppProdInfoType() {
        return new AppProdInfoType();
    }

}
