//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.vmp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.fhir.transform.xml.dmd.v2_3.vmp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.fhir.transform.xml.dmd.v2_3.vmp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS }
     * 
     */
    public VIRTUALMEDPRODUCTS createVIRTUALMEDPRODUCTS() {
        return new VIRTUALMEDPRODUCTS();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS.VMPS }
     * 
     */
    public VIRTUALMEDPRODUCTS.VMPS createVIRTUALMEDPRODUCTSVMPS() {
        return new VIRTUALMEDPRODUCTS.VMPS();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS.VIRTUALPRODUCTINGREDIENT }
     * 
     */
    public VIRTUALMEDPRODUCTS.VIRTUALPRODUCTINGREDIENT createVIRTUALMEDPRODUCTSVIRTUALPRODUCTINGREDIENT() {
        return new VIRTUALMEDPRODUCTS.VIRTUALPRODUCTINGREDIENT();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS.ONTDRUGFORM }
     * 
     */
    public VIRTUALMEDPRODUCTS.ONTDRUGFORM createVIRTUALMEDPRODUCTSONTDRUGFORM() {
        return new VIRTUALMEDPRODUCTS.ONTDRUGFORM();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS.DRUGFORM }
     * 
     */
    public VIRTUALMEDPRODUCTS.DRUGFORM createVIRTUALMEDPRODUCTSDRUGFORM() {
        return new VIRTUALMEDPRODUCTS.DRUGFORM();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS.DRUGROUTE }
     * 
     */
    public VIRTUALMEDPRODUCTS.DRUGROUTE createVIRTUALMEDPRODUCTSDRUGROUTE() {
        return new VIRTUALMEDPRODUCTS.DRUGROUTE();
    }

    /**
     * Create an instance of {@link VIRTUALMEDPRODUCTS.CONTROLDRUGINFO }
     * 
     */
    public VIRTUALMEDPRODUCTS.CONTROLDRUGINFO createVIRTUALMEDPRODUCTSCONTROLDRUGINFO() {
        return new VIRTUALMEDPRODUCTS.CONTROLDRUGINFO();
    }

    /**
     * Create an instance of {@link VmpType }
     * 
     */
    public VmpType createVmpType() {
        return new VmpType();
    }

    /**
     * Create an instance of {@link VpiType }
     * 
     */
    public VpiType createVpiType() {
        return new VpiType();
    }

    /**
     * Create an instance of {@link OntDrugFormType }
     * 
     */
    public OntDrugFormType createOntDrugFormType() {
        return new OntDrugFormType();
    }

    /**
     * Create an instance of {@link DrugFormType }
     * 
     */
    public DrugFormType createDrugFormType() {
        return new DrugFormType();
    }

    /**
     * Create an instance of {@link DrugRouteType }
     * 
     */
    public DrugRouteType createDrugRouteType() {
        return new DrugRouteType();
    }

    /**
     * Create an instance of {@link ControlInfoType }
     * 
     */
    public ControlInfoType createControlInfoType() {
        return new ControlInfoType();
    }

}
