//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.03 at 08:29:45 AM AEST 
//


package au.csiro.fhir.transforms.xml.dmd.v2_3.vmp;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VmpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VmpType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="VPID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="VPIDDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="VPIDPREV" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="VTMID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="INVALID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ABBREVNM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BASISCD" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="NMDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="NMPREV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BASIS_PREVCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NMCHANGECD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="COMBPRODCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="PRES_STATCD" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="SUG_F" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="GLU_F" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="PRES_F" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="CFC_F" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NON_AVAILCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NON_AVAILDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="DF_INDCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="UDFS" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="UDFS_UOMCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="UNIT_DOSE_UOMCD" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VmpType", propOrder = {

})
public class VmpType {

    @XmlElement(name = "VPID", required = true)
    protected BigInteger vpid;
    @XmlElement(name = "VPIDDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar vpiddt;
    @XmlElement(name = "VPIDPREV")
    protected BigInteger vpidprev;
    @XmlElement(name = "VTMID")
    protected BigInteger vtmid;
    @XmlElement(name = "INVALID")
    protected BigInteger invalid;
    @XmlElement(name = "NM", required = true)
    protected String nm;
    @XmlElement(name = "ABBREVNM")
    protected String abbrevnm;
    @XmlElement(name = "BASISCD", required = true)
    protected BigInteger basiscd;
    @XmlElement(name = "NMDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nmdt;
    @XmlElement(name = "NMPREV")
    protected String nmprev;
    @XmlElement(name = "BASIS_PREVCD")
    protected BigInteger basisprevcd;
    @XmlElement(name = "NMCHANGECD")
    protected BigInteger nmchangecd;
    @XmlElement(name = "COMBPRODCD")
    protected BigInteger combprodcd;
    @XmlElement(name = "PRES_STATCD", required = true)
    protected BigInteger presstatcd;
    @XmlElement(name = "SUG_F")
    protected BigInteger sugf;
    @XmlElement(name = "GLU_F")
    protected BigInteger gluf;
    @XmlElement(name = "PRES_F")
    protected BigInteger presf;
    @XmlElement(name = "CFC_F")
    protected BigInteger cfcf;
    @XmlElement(name = "NON_AVAILCD")
    protected BigInteger nonavailcd;
    @XmlElement(name = "NON_AVAILDT")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nonavaildt;
    @XmlElement(name = "DF_INDCD")
    protected BigInteger dfindcd;
    @XmlElement(name = "UDFS")
    protected Float udfs;
    @XmlElement(name = "UDFS_UOMCD")
    protected BigInteger udfsuomcd;
    @XmlElement(name = "UNIT_DOSE_UOMCD")
    protected BigInteger unitdoseuomcd;

    /**
     * Gets the value of the vpid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVPID() {
        return vpid;
    }

    /**
     * Sets the value of the vpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVPID(BigInteger value) {
        this.vpid = value;
    }

    /**
     * Gets the value of the vpiddt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVPIDDT() {
        return vpiddt;
    }

    /**
     * Sets the value of the vpiddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVPIDDT(XMLGregorianCalendar value) {
        this.vpiddt = value;
    }

    /**
     * Gets the value of the vpidprev property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVPIDPREV() {
        return vpidprev;
    }

    /**
     * Sets the value of the vpidprev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVPIDPREV(BigInteger value) {
        this.vpidprev = value;
    }

    /**
     * Gets the value of the vtmid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVTMID() {
        return vtmid;
    }

    /**
     * Sets the value of the vtmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVTMID(BigInteger value) {
        this.vtmid = value;
    }

    /**
     * Gets the value of the invalid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getINVALID() {
        return invalid;
    }

    /**
     * Sets the value of the invalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setINVALID(BigInteger value) {
        this.invalid = value;
    }

    /**
     * Gets the value of the nm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNM() {
        return nm;
    }

    /**
     * Sets the value of the nm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNM(String value) {
        this.nm = value;
    }

    /**
     * Gets the value of the abbrevnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABBREVNM() {
        return abbrevnm;
    }

    /**
     * Sets the value of the abbrevnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABBREVNM(String value) {
        this.abbrevnm = value;
    }

    /**
     * Gets the value of the basiscd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBASISCD() {
        return basiscd;
    }

    /**
     * Sets the value of the basiscd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBASISCD(BigInteger value) {
        this.basiscd = value;
    }

    /**
     * Gets the value of the nmdt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNMDT() {
        return nmdt;
    }

    /**
     * Sets the value of the nmdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNMDT(XMLGregorianCalendar value) {
        this.nmdt = value;
    }

    /**
     * Gets the value of the nmprev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMPREV() {
        return nmprev;
    }

    /**
     * Sets the value of the nmprev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMPREV(String value) {
        this.nmprev = value;
    }

    /**
     * Gets the value of the basisprevcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBASISPREVCD() {
        return basisprevcd;
    }

    /**
     * Sets the value of the basisprevcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBASISPREVCD(BigInteger value) {
        this.basisprevcd = value;
    }

    /**
     * Gets the value of the nmchangecd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNMCHANGECD() {
        return nmchangecd;
    }

    /**
     * Sets the value of the nmchangecd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNMCHANGECD(BigInteger value) {
        this.nmchangecd = value;
    }

    /**
     * Gets the value of the combprodcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOMBPRODCD() {
        return combprodcd;
    }

    /**
     * Sets the value of the combprodcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOMBPRODCD(BigInteger value) {
        this.combprodcd = value;
    }

    /**
     * Gets the value of the presstatcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPRESSTATCD() {
        return presstatcd;
    }

    /**
     * Sets the value of the presstatcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPRESSTATCD(BigInteger value) {
        this.presstatcd = value;
    }

    /**
     * Gets the value of the sugf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSUGF() {
        return sugf;
    }

    /**
     * Sets the value of the sugf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSUGF(BigInteger value) {
        this.sugf = value;
    }

    /**
     * Gets the value of the gluf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGLUF() {
        return gluf;
    }

    /**
     * Sets the value of the gluf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGLUF(BigInteger value) {
        this.gluf = value;
    }

    /**
     * Gets the value of the presf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPRESF() {
        return presf;
    }

    /**
     * Sets the value of the presf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPRESF(BigInteger value) {
        this.presf = value;
    }

    /**
     * Gets the value of the cfcf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCFCF() {
        return cfcf;
    }

    /**
     * Sets the value of the cfcf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCFCF(BigInteger value) {
        this.cfcf = value;
    }

    /**
     * Gets the value of the nonavailcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNONAVAILCD() {
        return nonavailcd;
    }

    /**
     * Sets the value of the nonavailcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNONAVAILCD(BigInteger value) {
        this.nonavailcd = value;
    }

    /**
     * Gets the value of the nonavaildt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNONAVAILDT() {
        return nonavaildt;
    }

    /**
     * Sets the value of the nonavaildt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNONAVAILDT(XMLGregorianCalendar value) {
        this.nonavaildt = value;
    }

    /**
     * Gets the value of the dfindcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDFINDCD() {
        return dfindcd;
    }

    /**
     * Sets the value of the dfindcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDFINDCD(BigInteger value) {
        this.dfindcd = value;
    }

    /**
     * Gets the value of the udfs property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getUDFS() {
        return udfs;
    }

    /**
     * Sets the value of the udfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setUDFS(Float value) {
        this.udfs = value;
    }

    /**
     * Gets the value of the udfsuomcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUDFSUOMCD() {
        return udfsuomcd;
    }

    /**
     * Sets the value of the udfsuomcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUDFSUOMCD(BigInteger value) {
        this.udfsuomcd = value;
    }

    /**
     * Gets the value of the unitdoseuomcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUNITDOSEUOMCD() {
        return unitdoseuomcd;
    }

    /**
     * Sets the value of the unitdoseuomcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUNITDOSEUOMCD(BigInteger value) {
        this.unitdoseuomcd = value;
    }

}
